// =============================================================================
// Access Management - Permission matrix
//
// Auto-generated by scripts/generate_specs.js from
//   testcases_excel/threatmodeler_7.x (11).xlsx
//   tests/data/traceability/access_management.json
//
// 454 source C-IDs covered: 0 runnable, 454 fixture-dependent.
// Fixture-dependent tests use test.fixme() with a documented fixture need
// so the C-ID shows up in the Playwright report but the test is reported
// as expected-to-fail rather than a regression. The fixtures themselves
// (multi-user role logins, CSV uploads, downloads, destructive writes)
// are tracked separately and will be filled in by follow-up suites.
// =============================================================================

import { test, expect, type Page } from "@playwright/test";
// @ts-ignore -- helpers.js is CommonJS
import { TIMEOUTS, login } from "./lib/helpers";
import { gotoAccessManagement, activateAccessManagementTab } from "./lib/am-helpers";
import testdata from "./data/testdata.json";

const AM = testdata.accessManagement;

test.describe("Access Management - Permission matrix", () => {
  test.setTimeout(TIMEOUTS.test);

  test.fixme("cancel_dialog [C17774] -- needs multi-user-role-login", async ({ page }, info) => {
        info.annotations.push({ type: "case", description: "C17774" });
        // Sample case title: "Verify that the Close button or Cancel action aborts the mod"
        // Total C-IDs in this bucket: 1
        // Fixture required: multi-user-role-login
        // When the fixture is available, replace fixme with an
        // implementation that exercises cancel_dialog for each ID listed.
      });

  test.fixme("delete [C14405, C14440, C14453, C14463, C14479 +19 more] -- needs multi-user-role-login", async ({ page }, info) => {
        info.annotations.push({ type: "case", description: "C14405" });
        info.annotations.push({ type: "case", description: "C14440" });
        info.annotations.push({ type: "case", description: "C14453" });
        info.annotations.push({ type: "case", description: "C14463" });
        info.annotations.push({ type: "case", description: "C14479" });
        info.annotations.push({ type: "case", description: "C14487" });
        info.annotations.push({ type: "case", description: "C14488" });
        info.annotations.push({ type: "case", description: "C14496" });
        info.annotations.push({ type: "case", description: "C14522" });
        info.annotations.push({ type: "case", description: "C14523" });
        info.annotations.push({ type: "case", description: "C14555" });
        info.annotations.push({ type: "case", description: "C14568" });
        info.annotations.push({ type: "case", description: "C14574" });
        info.annotations.push({ type: "case", description: "C14587" });
        info.annotations.push({ type: "case", description: "C14594" });
        info.annotations.push({ type: "case", description: "C14595" });
        info.annotations.push({ type: "case", description: "C14603" });
        info.annotations.push({ type: "case", description: "C14627" });
        info.annotations.push({ type: "case", description: "C14656" });
        info.annotations.push({ type: "case", description: "C14672" });
        info.annotations.push({ type: "case", description: "C14712" });
        info.annotations.push({ type: "case", description: "C17778" });
        info.annotations.push({ type: "case", description: "C17805" });
        info.annotations.push({ type: "case", description: "C17806" });
        // Sample case title: "Check if user with ''Enterprise > Administrator > All'' perm"
        // Total C-IDs in this bucket: 24
        // Fixture required: multi-user-role-login
        // When the fixture is available, replace fixme with an
        // implementation that exercises delete for each ID listed.
      });

  test.fixme("dropdown [C17789, C17790, C17803, C17804, C17809, C17810] -- needs multi-user-role-login", async ({ page }, info) => {
        info.annotations.push({ type: "case", description: "C17789" });
        info.annotations.push({ type: "case", description: "C17790" });
        info.annotations.push({ type: "case", description: "C17803" });
        info.annotations.push({ type: "case", description: "C17804" });
        info.annotations.push({ type: "case", description: "C17809" });
        info.annotations.push({ type: "case", description: "C17810" });
        // Sample case title: "Verify that the users dropdown shows only current department"
        // Total C-IDs in this bucket: 6
        // Fixture required: multi-user-role-login
        // When the fixture is available, replace fixme with an
        // implementation that exercises dropdown for each ID listed.
      });

  test.fixme("edit [C14406, C14413, C14420, C14423, C14424 +91 more] -- needs multi-user-role-login", async ({ page }, info) => {
        info.annotations.push({ type: "case", description: "C14406" });
        info.annotations.push({ type: "case", description: "C14413" });
        info.annotations.push({ type: "case", description: "C14420" });
        info.annotations.push({ type: "case", description: "C14423" });
        info.annotations.push({ type: "case", description: "C14424" });
        info.annotations.push({ type: "case", description: "C14434" });
        info.annotations.push({ type: "case", description: "C14439" });
        info.annotations.push({ type: "case", description: "C14450" });
        info.annotations.push({ type: "case", description: "C14462" });
        info.annotations.push({ type: "case", description: "C14475" });
        info.annotations.push({ type: "case", description: "C14481" });
        info.annotations.push({ type: "case", description: "C14482" });
        info.annotations.push({ type: "case", description: "C14492" });
        info.annotations.push({ type: "case", description: "C14500" });
        info.annotations.push({ type: "case", description: "C14501" });
        info.annotations.push({ type: "case", description: "C14503" });
        info.annotations.push({ type: "case", description: "C14508" });
        info.annotations.push({ type: "case", description: "C14512" });
        info.annotations.push({ type: "case", description: "C14513" });
        info.annotations.push({ type: "case", description: "C14515" });
        info.annotations.push({ type: "case", description: "C14520" });
        info.annotations.push({ type: "case", description: "C14528" });
        info.annotations.push({ type: "case", description: "C14529" });
        info.annotations.push({ type: "case", description: "C14531" });
        info.annotations.push({ type: "case", description: "C14536" });
        info.annotations.push({ type: "case", description: "C14538" });
        info.annotations.push({ type: "case", description: "C14539" });
        info.annotations.push({ type: "case", description: "C14549" });
        info.annotations.push({ type: "case", description: "C14554" });
        info.annotations.push({ type: "case", description: "C14563" });
        info.annotations.push({ type: "case", description: "C14573" });
        info.annotations.push({ type: "case", description: "C14583" });
        info.annotations.push({ type: "case", description: "C14589" });
        info.annotations.push({ type: "case", description: "C14599" });
        info.annotations.push({ type: "case", description: "C14607" });
        info.annotations.push({ type: "case", description: "C14608" });
        info.annotations.push({ type: "case", description: "C14610" });
        info.annotations.push({ type: "case", description: "C14615" });
        info.annotations.push({ type: "case", description: "C14617" });
        info.annotations.push({ type: "case", description: "C14618" });
        info.annotations.push({ type: "case", description: "C14620" });
        info.annotations.push({ type: "case", description: "C14625" });
        info.annotations.push({ type: "case", description: "C14631" });
        info.annotations.push({ type: "case", description: "C14632" });
        info.annotations.push({ type: "case", description: "C14634" });
        info.annotations.push({ type: "case", description: "C14639" });
        info.annotations.push({ type: "case", description: "C14641" });
        info.annotations.push({ type: "case", description: "C14643" });
        info.annotations.push({ type: "case", description: "C14653" });
        info.annotations.push({ type: "case", description: "C14657" });
        info.annotations.push({ type: "case", description: "C14659" });
        info.annotations.push({ type: "case", description: "C14668" });
        info.annotations.push({ type: "case", description: "C14673" });
        info.annotations.push({ type: "case", description: "C14678" });
        info.annotations.push({ type: "case", description: "C14680" });
        info.annotations.push({ type: "case", description: "C14687" });
        info.annotations.push({ type: "case", description: "C14698" });
        info.annotations.push({ type: "case", description: "C14705" });
        info.annotations.push({ type: "case", description: "C14708" });
        info.annotations.push({ type: "case", description: "C14711" });
        info.annotations.push({ type: "case", description: "C16243" });
        info.annotations.push({ type: "case", description: "C16244" });
        info.annotations.push({ type: "case", description: "C17751" });
        info.annotations.push({ type: "case", description: "C17752" });
        info.annotations.push({ type: "case", description: "C17753" });
        info.annotations.push({ type: "case", description: "C17754" });
        info.annotations.push({ type: "case", description: "C17755" });
        info.annotations.push({ type: "case", description: "C17757" });
        info.annotations.push({ type: "case", description: "C17759" });
        info.annotations.push({ type: "case", description: "C17761" });
        info.annotations.push({ type: "case", description: "C17763" });
        info.annotations.push({ type: "case", description: "C17765" });
        info.annotations.push({ type: "case", description: "C17767" });
        info.annotations.push({ type: "case", description: "C17769" });
        info.annotations.push({ type: "case", description: "C17771" });
        info.annotations.push({ type: "case", description: "C17773" });
        info.annotations.push({ type: "case", description: "C17775" });
        info.annotations.push({ type: "case", description: "C17776" });
        info.annotations.push({ type: "case", description: "C17777" });
        info.annotations.push({ type: "case", description: "C17779" });
        info.annotations.push({ type: "case", description: "C17781" });
        info.annotations.push({ type: "case", description: "C17782" });
        info.annotations.push({ type: "case", description: "C17787" });
        info.annotations.push({ type: "case", description: "C17788" });
        info.annotations.push({ type: "case", description: "C17795" });
        info.annotations.push({ type: "case", description: "C17796" });
        info.annotations.push({ type: "case", description: "C17797" });
        info.annotations.push({ type: "case", description: "C17798" });
        info.annotations.push({ type: "case", description: "C18036" });
        info.annotations.push({ type: "case", description: "C18039" });
        info.annotations.push({ type: "case", description: "C18042" });
        info.annotations.push({ type: "case", description: "C18057" });
        info.annotations.push({ type: "case", description: "C18060" });
        info.annotations.push({ type: "case", description: "C18063" });
        info.annotations.push({ type: "case", description: "C18073" });
        info.annotations.push({ type: "case", description: "C18092" });
        // Sample case title: "Check if user with ''Enterprise > Administrator > All'' perm"
        // Total C-IDs in this bucket: 96
        // Fixture required: multi-user-role-login
        // When the fixture is available, replace fixme with an
        // implementation that exercises edit for each ID listed.
      });

  test.fixme("export_import [C14408, C14409, C14414, C14422, C14425 +97 more] -- needs multi-user-role-login", async ({ page }, info) => {
        info.annotations.push({ type: "case", description: "C14408" });
        info.annotations.push({ type: "case", description: "C14409" });
        info.annotations.push({ type: "case", description: "C14414" });
        info.annotations.push({ type: "case", description: "C14422" });
        info.annotations.push({ type: "case", description: "C14425" });
        info.annotations.push({ type: "case", description: "C14426" });
        info.annotations.push({ type: "case", description: "C14427" });
        info.annotations.push({ type: "case", description: "C14438" });
        info.annotations.push({ type: "case", description: "C14473" });
        info.annotations.push({ type: "case", description: "C14498" });
        info.annotations.push({ type: "case", description: "C14499" });
        info.annotations.push({ type: "case", description: "C14502" });
        info.annotations.push({ type: "case", description: "C14504" });
        info.annotations.push({ type: "case", description: "C14505" });
        info.annotations.push({ type: "case", description: "C14506" });
        info.annotations.push({ type: "case", description: "C14507" });
        info.annotations.push({ type: "case", description: "C14509" });
        info.annotations.push({ type: "case", description: "C14510" });
        info.annotations.push({ type: "case", description: "C14511" });
        info.annotations.push({ type: "case", description: "C14514" });
        info.annotations.push({ type: "case", description: "C14516" });
        info.annotations.push({ type: "case", description: "C14517" });
        info.annotations.push({ type: "case", description: "C14518" });
        info.annotations.push({ type: "case", description: "C14519" });
        info.annotations.push({ type: "case", description: "C14521" });
        info.annotations.push({ type: "case", description: "C14524" });
        info.annotations.push({ type: "case", description: "C14525" });
        info.annotations.push({ type: "case", description: "C14526" });
        info.annotations.push({ type: "case", description: "C14527" });
        info.annotations.push({ type: "case", description: "C14530" });
        info.annotations.push({ type: "case", description: "C14532" });
        info.annotations.push({ type: "case", description: "C14533" });
        info.annotations.push({ type: "case", description: "C14534" });
        info.annotations.push({ type: "case", description: "C14535" });
        info.annotations.push({ type: "case", description: "C14537" });
        info.annotations.push({ type: "case", description: "C14540" });
        info.annotations.push({ type: "case", description: "C14541" });
        info.annotations.push({ type: "case", description: "C14542" });
        info.annotations.push({ type: "case", description: "C14553" });
        info.annotations.push({ type: "case", description: "C14582" });
        info.annotations.push({ type: "case", description: "C14605" });
        info.annotations.push({ type: "case", description: "C14606" });
        info.annotations.push({ type: "case", description: "C14609" });
        info.annotations.push({ type: "case", description: "C14611" });
        info.annotations.push({ type: "case", description: "C14612" });
        info.annotations.push({ type: "case", description: "C14613" });
        info.annotations.push({ type: "case", description: "C14614" });
        info.annotations.push({ type: "case", description: "C14616" });
        info.annotations.push({ type: "case", description: "C14619" });
        info.annotations.push({ type: "case", description: "C14621" });
        info.annotations.push({ type: "case", description: "C14622" });
        info.annotations.push({ type: "case", description: "C14623" });
        info.annotations.push({ type: "case", description: "C14624" });
        info.annotations.push({ type: "case", description: "C14626" });
        info.annotations.push({ type: "case", description: "C14628" });
        info.annotations.push({ type: "case", description: "C14629" });
        info.annotations.push({ type: "case", description: "C14630" });
        info.annotations.push({ type: "case", description: "C14633" });
        info.annotations.push({ type: "case", description: "C14635" });
        info.annotations.push({ type: "case", description: "C14636" });
        info.annotations.push({ type: "case", description: "C14637" });
        info.annotations.push({ type: "case", description: "C14638" });
        info.annotations.push({ type: "case", description: "C14640" });
        info.annotations.push({ type: "case", description: "C14644" });
        info.annotations.push({ type: "case", description: "C14645" });
        info.annotations.push({ type: "case", description: "C14646" });
        info.annotations.push({ type: "case", description: "C14660" });
        info.annotations.push({ type: "case", description: "C14661" });
        info.annotations.push({ type: "case", description: "C14662" });
        info.annotations.push({ type: "case", description: "C14675" });
        info.annotations.push({ type: "case", description: "C14676" });
        info.annotations.push({ type: "case", description: "C14681" });
        info.annotations.push({ type: "case", description: "C14689" });
        info.annotations.push({ type: "case", description: "C14693" });
        info.annotations.push({ type: "case", description: "C14694" });
        info.annotations.push({ type: "case", description: "C14695" });
        info.annotations.push({ type: "case", description: "C14696" });
        info.annotations.push({ type: "case", description: "C14697" });
        info.annotations.push({ type: "case", description: "C14699" });
        info.annotations.push({ type: "case", description: "C14700" });
        info.annotations.push({ type: "case", description: "C14701" });
        info.annotations.push({ type: "case", description: "C14703" });
        info.annotations.push({ type: "case", description: "C14704" });
        info.annotations.push({ type: "case", description: "C14706" });
        info.annotations.push({ type: "case", description: "C14707" });
        info.annotations.push({ type: "case", description: "C14709" });
        info.annotations.push({ type: "case", description: "C14710" });
        info.annotations.push({ type: "case", description: "C14714" });
        info.annotations.push({ type: "case", description: "C18033" });
        info.annotations.push({ type: "case", description: "C18034" });
        info.annotations.push({ type: "case", description: "C18035" });
        info.annotations.push({ type: "case", description: "C18045" });
        info.annotations.push({ type: "case", description: "C18054" });
        info.annotations.push({ type: "case", description: "C18055" });
        info.annotations.push({ type: "case", description: "C18056" });
        info.annotations.push({ type: "case", description: "C18066" });
        info.annotations.push({ type: "case", description: "C18076" });
        info.annotations.push({ type: "case", description: "C18077" });
        info.annotations.push({ type: "case", description: "C18085" });
        info.annotations.push({ type: "case", description: "C18095" });
        info.annotations.push({ type: "case", description: "C18096" });
        info.annotations.push({ type: "case", description: "C18104" });
        // Sample case title: "Check if user with ''Enterprise > Auditor > Read Only'' perm"
        // Total C-IDs in this bucket: 102
        // Fixture required: multi-user-role-login
        // When the fixture is available, replace fixme with an
        // implementation that exercises export_import for each ID listed.
      });

  test.fixme("other [C14702, C17770, C17772, C17780, C17791 +26 more] -- needs multi-user-role-login", async ({ page }, info) => {
        info.annotations.push({ type: "case", description: "C14702" });
        info.annotations.push({ type: "case", description: "C17770" });
        info.annotations.push({ type: "case", description: "C17772" });
        info.annotations.push({ type: "case", description: "C17780" });
        info.annotations.push({ type: "case", description: "C17791" });
        info.annotations.push({ type: "case", description: "C17792" });
        info.annotations.push({ type: "case", description: "C17799" });
        info.annotations.push({ type: "case", description: "C17800" });
        info.annotations.push({ type: "case", description: "C17801" });
        info.annotations.push({ type: "case", description: "C17802" });
        info.annotations.push({ type: "case", description: "C17807" });
        info.annotations.push({ type: "case", description: "C17808" });
        info.annotations.push({ type: "case", description: "C18031" });
        info.annotations.push({ type: "case", description: "C18040" });
        info.annotations.push({ type: "case", description: "C18070" });
        info.annotations.push({ type: "case", description: "C18071" });
        info.annotations.push({ type: "case", description: "C18074" });
        info.annotations.push({ type: "case", description: "C18075" });
        info.annotations.push({ type: "case", description: "C18079" });
        info.annotations.push({ type: "case", description: "C18081" });
        info.annotations.push({ type: "case", description: "C18083" });
        info.annotations.push({ type: "case", description: "C18086" });
        info.annotations.push({ type: "case", description: "C18089" });
        info.annotations.push({ type: "case", description: "C18090" });
        info.annotations.push({ type: "case", description: "C18093" });
        info.annotations.push({ type: "case", description: "C18094" });
        info.annotations.push({ type: "case", description: "C18098" });
        info.annotations.push({ type: "case", description: "C18100" });
        info.annotations.push({ type: "case", description: "C18102" });
        info.annotations.push({ type: "case", description: "C18106" });
        info.annotations.push({ type: "case", description: "C18107" });
        // Sample case title: "Check if user can Create a New Version in ALL Threat Models "
        // Total C-IDs in this bucket: 31
        // Fixture required: multi-user-role-login
        // When the fixture is available, replace fixme with an
        // implementation that exercises other for each ID listed.
      });

  test.fixme("permission [C14401, C14402, C14403, C14404, C16882 +174 more] -- needs multi-user-role-login", async ({ page }, info) => {
        info.annotations.push({ type: "case", description: "C14401" });
        info.annotations.push({ type: "case", description: "C14402" });
        info.annotations.push({ type: "case", description: "C14403" });
        info.annotations.push({ type: "case", description: "C14404" });
        info.annotations.push({ type: "case", description: "C16882" });
        info.annotations.push({ type: "case", description: "C14410" });
        info.annotations.push({ type: "case", description: "C14411" });
        info.annotations.push({ type: "case", description: "C14412" });
        info.annotations.push({ type: "case", description: "C14415" });
        info.annotations.push({ type: "case", description: "C14416" });
        info.annotations.push({ type: "case", description: "C14417" });
        info.annotations.push({ type: "case", description: "C14418" });
        info.annotations.push({ type: "case", description: "C14419" });
        info.annotations.push({ type: "case", description: "C14421" });
        info.annotations.push({ type: "case", description: "C14428" });
        info.annotations.push({ type: "case", description: "C14429" });
        info.annotations.push({ type: "case", description: "C14430" });
        info.annotations.push({ type: "case", description: "C14431" });
        info.annotations.push({ type: "case", description: "C14432" });
        info.annotations.push({ type: "case", description: "C14433" });
        info.annotations.push({ type: "case", description: "C14435" });
        info.annotations.push({ type: "case", description: "C14436" });
        info.annotations.push({ type: "case", description: "C14437" });
        info.annotations.push({ type: "case", description: "C14442" });
        info.annotations.push({ type: "case", description: "C14445" });
        info.annotations.push({ type: "case", description: "C14446" });
        info.annotations.push({ type: "case", description: "C14447" });
        info.annotations.push({ type: "case", description: "C14448" });
        info.annotations.push({ type: "case", description: "C14449" });
        info.annotations.push({ type: "case", description: "C14451" });
        info.annotations.push({ type: "case", description: "C14452" });
        info.annotations.push({ type: "case", description: "C14457" });
        info.annotations.push({ type: "case", description: "C14458" });
        info.annotations.push({ type: "case", description: "C14459" });
        info.annotations.push({ type: "case", description: "C14460" });
        info.annotations.push({ type: "case", description: "C14461" });
        info.annotations.push({ type: "case", description: "C14465" });
        info.annotations.push({ type: "case", description: "C14468" });
        info.annotations.push({ type: "case", description: "C14469" });
        info.annotations.push({ type: "case", description: "C14470" });
        info.annotations.push({ type: "case", description: "C14471" });
        info.annotations.push({ type: "case", description: "C14472" });
        info.annotations.push({ type: "case", description: "C14474" });
        info.annotations.push({ type: "case", description: "C14476" });
        info.annotations.push({ type: "case", description: "C14477" });
        info.annotations.push({ type: "case", description: "C14478" });
        info.annotations.push({ type: "case", description: "C14480" });
        info.annotations.push({ type: "case", description: "C14483" });
        info.annotations.push({ type: "case", description: "C14484" });
        info.annotations.push({ type: "case", description: "C14485" });
        info.annotations.push({ type: "case", description: "C14486" });
        info.annotations.push({ type: "case", description: "C14489" });
        info.annotations.push({ type: "case", description: "C14490" });
        info.annotations.push({ type: "case", description: "C14491" });
        info.annotations.push({ type: "case", description: "C14493" });
        info.annotations.push({ type: "case", description: "C14494" });
        info.annotations.push({ type: "case", description: "C14495" });
        info.annotations.push({ type: "case", description: "C14497" });
        info.annotations.push({ type: "case", description: "C14543" });
        info.annotations.push({ type: "case", description: "C14544" });
        info.annotations.push({ type: "case", description: "C14545" });
        info.annotations.push({ type: "case", description: "C14546" });
        info.annotations.push({ type: "case", description: "C14547" });
        info.annotations.push({ type: "case", description: "C14548" });
        info.annotations.push({ type: "case", description: "C14550" });
        info.annotations.push({ type: "case", description: "C14551" });
        info.annotations.push({ type: "case", description: "C14552" });
        info.annotations.push({ type: "case", description: "C14557" });
        info.annotations.push({ type: "case", description: "C14559" });
        info.annotations.push({ type: "case", description: "C14560" });
        info.annotations.push({ type: "case", description: "C14561" });
        info.annotations.push({ type: "case", description: "C14562" });
        info.annotations.push({ type: "case", description: "C14564" });
        info.annotations.push({ type: "case", description: "C14566" });
        info.annotations.push({ type: "case", description: "C14567" });
        info.annotations.push({ type: "case", description: "C14570" });
        info.annotations.push({ type: "case", description: "C14571" });
        info.annotations.push({ type: "case", description: "C14572" });
        info.annotations.push({ type: "case", description: "C14576" });
        info.annotations.push({ type: "case", description: "C14577" });
        info.annotations.push({ type: "case", description: "C14578" });
        info.annotations.push({ type: "case", description: "C14579" });
        info.annotations.push({ type: "case", description: "C14580" });
        info.annotations.push({ type: "case", description: "C14581" });
        info.annotations.push({ type: "case", description: "C14584" });
        info.annotations.push({ type: "case", description: "C14585" });
        info.annotations.push({ type: "case", description: "C14586" });
        info.annotations.push({ type: "case", description: "C14588" });
        info.annotations.push({ type: "case", description: "C14590" });
        info.annotations.push({ type: "case", description: "C14591" });
        info.annotations.push({ type: "case", description: "C14592" });
        info.annotations.push({ type: "case", description: "C14593" });
        info.annotations.push({ type: "case", description: "C14596" });
        info.annotations.push({ type: "case", description: "C14597" });
        info.annotations.push({ type: "case", description: "C14598" });
        info.annotations.push({ type: "case", description: "C14600" });
        info.annotations.push({ type: "case", description: "C14601" });
        info.annotations.push({ type: "case", description: "C14602" });
        info.annotations.push({ type: "case", description: "C14604" });
        info.annotations.push({ type: "case", description: "C14642" });
        info.annotations.push({ type: "case", description: "C14647" });
        info.annotations.push({ type: "case", description: "C14648" });
        info.annotations.push({ type: "case", description: "C14649" });
        info.annotations.push({ type: "case", description: "C14650" });
        info.annotations.push({ type: "case", description: "C14651" });
        info.annotations.push({ type: "case", description: "C14652" });
        info.annotations.push({ type: "case", description: "C14654" });
        info.annotations.push({ type: "case", description: "C14655" });
        info.annotations.push({ type: "case", description: "C14658" });
        info.annotations.push({ type: "case", description: "C14663" });
        info.annotations.push({ type: "case", description: "C14664" });
        info.annotations.push({ type: "case", description: "C14665" });
        info.annotations.push({ type: "case", description: "C14666" });
        info.annotations.push({ type: "case", description: "C14667" });
        info.annotations.push({ type: "case", description: "C14669" });
        info.annotations.push({ type: "case", description: "C14670" });
        info.annotations.push({ type: "case", description: "C14671" });
        info.annotations.push({ type: "case", description: "C14677" });
        info.annotations.push({ type: "case", description: "C14679" });
        info.annotations.push({ type: "case", description: "C14682" });
        info.annotations.push({ type: "case", description: "C14683" });
        info.annotations.push({ type: "case", description: "C14684" });
        info.annotations.push({ type: "case", description: "C14685" });
        info.annotations.push({ type: "case", description: "C14686" });
        info.annotations.push({ type: "case", description: "C14688" });
        info.annotations.push({ type: "case", description: "C14690" });
        info.annotations.push({ type: "case", description: "C14691" });
        info.annotations.push({ type: "case", description: "C14692" });
        info.annotations.push({ type: "case", description: "C17749" });
        info.annotations.push({ type: "case", description: "C17750" });
        info.annotations.push({ type: "case", description: "C17756" });
        info.annotations.push({ type: "case", description: "C17758" });
        info.annotations.push({ type: "case", description: "C17760" });
        info.annotations.push({ type: "case", description: "C17762" });
        info.annotations.push({ type: "case", description: "C17764" });
        info.annotations.push({ type: "case", description: "C17766" });
        info.annotations.push({ type: "case", description: "C17768" });
        info.annotations.push({ type: "case", description: "C17783" });
        info.annotations.push({ type: "case", description: "C17784" });
        info.annotations.push({ type: "case", description: "C17811" });
        info.annotations.push({ type: "case", description: "C17812" });
        info.annotations.push({ type: "case", description: "C18027" });
        info.annotations.push({ type: "case", description: "C18028" });
        info.annotations.push({ type: "case", description: "C18029" });
        info.annotations.push({ type: "case", description: "C18030" });
        info.annotations.push({ type: "case", description: "C18037" });
        info.annotations.push({ type: "case", description: "C18038" });
        info.annotations.push({ type: "case", description: "C18041" });
        info.annotations.push({ type: "case", description: "C18043" });
        info.annotations.push({ type: "case", description: "C18044" });
        info.annotations.push({ type: "case", description: "C18046" });
        info.annotations.push({ type: "case", description: "C18047" });
        info.annotations.push({ type: "case", description: "C18048" });
        info.annotations.push({ type: "case", description: "C18049" });
        info.annotations.push({ type: "case", description: "C18050" });
        info.annotations.push({ type: "case", description: "C18051" });
        info.annotations.push({ type: "case", description: "C18052" });
        info.annotations.push({ type: "case", description: "C18058" });
        info.annotations.push({ type: "case", description: "C18059" });
        info.annotations.push({ type: "case", description: "C18061" });
        info.annotations.push({ type: "case", description: "C18062" });
        info.annotations.push({ type: "case", description: "C18064" });
        info.annotations.push({ type: "case", description: "C18065" });
        info.annotations.push({ type: "case", description: "C18067" });
        info.annotations.push({ type: "case", description: "C18068" });
        info.annotations.push({ type: "case", description: "C18069" });
        info.annotations.push({ type: "case", description: "C18072" });
        info.annotations.push({ type: "case", description: "C18078" });
        info.annotations.push({ type: "case", description: "C18080" });
        info.annotations.push({ type: "case", description: "C18082" });
        info.annotations.push({ type: "case", description: "C18084" });
        info.annotations.push({ type: "case", description: "C18087" });
        info.annotations.push({ type: "case", description: "C18088" });
        info.annotations.push({ type: "case", description: "C18091" });
        info.annotations.push({ type: "case", description: "C18097" });
        info.annotations.push({ type: "case", description: "C18099" });
        info.annotations.push({ type: "case", description: "C18101" });
        info.annotations.push({ type: "case", description: "C18103" });
        info.annotations.push({ type: "case", description: "C18105" });
        // Sample case title: "Check if user with ''Enterprise > Administrator > All'' perm"
        // Total C-IDs in this bucket: 179
        // Fixture required: multi-user-role-login
        // When the fixture is available, replace fixme with an
        // implementation that exercises permission for each ID listed.
      });

  test.fixme("render [C17785, C17786] -- needs multi-user-role-login", async ({ page }, info) => {
        info.annotations.push({ type: "case", description: "C17785" });
        info.annotations.push({ type: "case", description: "C17786" });
        // Sample case title: "Verify that clicking on a model name from the ''User Owns Mo"
        // Total C-IDs in this bucket: 2
        // Fixture required: multi-user-role-login
        // When the fixture is available, replace fixme with an
        // implementation that exercises render for each ID listed.
      });

  test.fixme("status_change [C14407, C14441, C14454, C14464, C14556 +8 more] -- needs multi-user-role-login", async ({ page }, info) => {
        info.annotations.push({ type: "case", description: "C14407" });
        info.annotations.push({ type: "case", description: "C14441" });
        info.annotations.push({ type: "case", description: "C14454" });
        info.annotations.push({ type: "case", description: "C14464" });
        info.annotations.push({ type: "case", description: "C14556" });
        info.annotations.push({ type: "case", description: "C14569" });
        info.annotations.push({ type: "case", description: "C14575" });
        info.annotations.push({ type: "case", description: "C14674" });
        info.annotations.push({ type: "case", description: "C14713" });
        info.annotations.push({ type: "case", description: "C17793" });
        info.annotations.push({ type: "case", description: "C17794" });
        info.annotations.push({ type: "case", description: "C18032" });
        info.annotations.push({ type: "case", description: "C18053" });
        // Sample case title: "Check if user with ''Enterprise > Auditor > Read Only'' perm"
        // Total C-IDs in this bucket: 13
        // Fixture required: multi-user-role-login
        // When the fixture is available, replace fixme with an
        // implementation that exercises status_change for each ID listed.
      });

});
