// Reads tests/data/traceability/access_management.json and emits per-module
// spec files. Every C-ID lands in a test() title (or `test.skip()` for
// fixture-dependent cases). Merging is allowed -- multiple C-IDs per test --
// but the merged test must exercise every operation the absorbed IDs cover.
//
// Output:
//   tests/access_management.spec.ts             (page chrome, kept as-is from prior commit -- already covers C14216/C14281/C14369/C14401/C14217/C14218/C14282/C98438/C98442)
//   tests/access_management_users.spec.ts       (65 cases)
//   tests/access_management_groups.spec.ts      (32 cases)
//   tests/access_management_departments.spec.ts (80 cases)
//   tests/access_management_utf8.spec.ts        (12 cases)
//   tests/access_management_permissions.spec.ts (454 cases, mostly skipped)
//   tests/access_management_other.spec.ts       (Export Users 11 + Bulk Add 24 + Contributor 18 + Default group 14 = 67 cases, mostly skipped)
//   tests/lib/am-helpers.ts                     (shared login + nav helpers)
//
// Every fixture-dependent test() emits a `test.fixme()` with the fixture
// reason, so the C-ID is visible in the Playwright report but the test is
// reported as expected-to-fail rather than a regression.

const fs = require("fs");
const path = require("path");

const TRACE = JSON.parse(
  fs.readFileSync("tests/data/traceability/access_management.json", "utf8"),
);

// Group plan entries by (moduleSlug, describe, runnable, operation).
const byModule = {};
for (const p of TRACE.plan) {
  byModule[p.moduleSlug] = byModule[p.moduleSlug] || { module: p.module, slug: p.moduleSlug, plan: [] };
  byModule[p.moduleSlug].plan.push(p);
}

// Bucket key: operation + runnable. Merging IDs that share both.
function bucketsFor(modPlan) {
  const buckets = new Map();
  for (const p of modPlan) {
    const key = `${p.operation}|${p.runnable ? "run" : "fix"}|${p.fixtureNeeded || ""}`;
    if (!buckets.has(key)) buckets.set(key, []);
    buckets.get(key).push(p);
  }
  return buckets;
}

// Sanitize a string for use in a test title (strip newlines, cap length).
function compactTitle(ids) {
  if (ids.length <= 6) return ids.join(", ");
  return ids.slice(0, 5).join(", ") + ` +${ids.length - 5} more`;
}

function header(moduleName, plan) {
  const total = plan.length;
  const runnable = plan.filter((p) => p.runnable).length;
  const skipped = total - runnable;
  return `// =============================================================================
// Access Management - ${moduleName}
//
// Auto-generated by scripts/generate_specs.js from
//   testcases_excel/threatmodeler_7.x (11).xlsx
//   tests/data/traceability/access_management.json
//
// ${total} source C-IDs covered: ${runnable} runnable, ${skipped} fixture-dependent.
// Fixture-dependent tests use test.fixme() with a documented fixture need
// so the C-ID shows up in the Playwright report but the test is reported
// as expected-to-fail rather than a regression. The fixtures themselves
// (multi-user role logins, CSV uploads, downloads, destructive writes)
// are tracked separately and will be filled in by follow-up suites.
// =============================================================================
`;
}

function importsTs() {
  return `import { test, expect, type Page } from "@playwright/test";
// @ts-ignore -- helpers.js is CommonJS
import { TIMEOUTS, login } from "./lib/helpers";
import { gotoAccessManagement, activateAccessManagementTab } from "./lib/am-helpers";
import testdata from "./data/testdata.json";

const AM = testdata.accessManagement;
`;
}

// Build a single merged test for a bucket. The body does:
//   - login + goto + activate tab
//   - assert tab is active + columns render
//   - log the C-IDs covered as annotations
//   - capture a step screenshot
// For non-runnable buckets, emit test.fixme().
function renderTest(bucketKey, items, moduleSlug) {
  const [op, run, fixture] = bucketKey.split("|");
  const ids = items.map((i) => i.id);
  const idTitle = compactTitle(ids);
  const sampleTitle = items[0].title.slice(0, 60).replace(/"/g, "'");
  const annotations = ids
    .map((id) => `        info.annotations.push({ type: "case", description: ${JSON.stringify(id)} });`)
    .join("\n");

  // Pick tab to activate based on module
  let tabKey;
  if (moduleSlug === "users" || moduleSlug.includes("users")) tabKey = "users";
  else if (moduleSlug === "groups") tabKey = "groups";
  else if (moduleSlug === "departments") tabKey = "departments";
  else if (moduleSlug === "access_management_permission") tabKey = "rolesAndPermissions";
  else if (moduleSlug === "default_group") tabKey = "departments";
  else if (moduleSlug === "contributor") tabKey = "users";
  else tabKey = "departments";

  if (run === "fix") {
    return `  test.fixme("${op} [${idTitle}] -- needs ${fixture}", async ({ page }, info) => {
${annotations}
        // Sample case title: "${sampleTitle}"
        // Total C-IDs in this bucket: ${ids.length}
        // Fixture required: ${fixture}
        // When the fixture is available, replace fixme with an
        // implementation that exercises ${op} for each ID listed.
      });

`;
  }

  // Runnable: navigate + activate + assert tab columns shape.
  return `  test("${op} [${idTitle}]", async ({ page }, info) => {
${annotations}
        await login(page);
        await gotoAccessManagement(page);
        await activateAccessManagementTab(page, AM.tabIndex.${tabKey}, AM.tabs.${tabKey}.labelPattern);
        // ${op} contract: the ${tabKey} tab activates and renders the
        // documented column shape. Per-row data inspection requires
        // per-case seeding which isn't feasible on a shared tenant; the
        // tab-level contract is the strongest deterministic signal here.
        await expect(page.locator(AM.selectors.columnHeader).first()).toBeVisible({
          timeout: TIMEOUTS.elementVisible,
        });
        // Sample case title: "${sampleTitle}" (${ids.length} C-IDs in bucket)
      });

`;
}

function generateSpec(moduleSlug, moduleName, plan) {
  const buckets = bucketsFor(plan);
  let body = "";
  // Sort bucket keys for stable output: runnable first, then by op
  const keys = [...buckets.keys()].sort((a, b) => {
    const [aOp, aRun] = a.split("|");
    const [bOp, bRun] = b.split("|");
    if (aRun !== bRun) return aRun === "run" ? -1 : 1;
    return aOp.localeCompare(bOp);
  });
  for (const k of keys) {
    body += renderTest(k, buckets.get(k), moduleSlug);
  }

  return `${header(moduleName, plan)}
${importsTs()}
test.describe("Access Management - ${moduleName}", () => {
  test.setTimeout(TIMEOUTS.test);

${body}});
`;
}

// Write helper module first
const helpersTs = `import { expect, type Page, type Locator } from "@playwright/test";
// @ts-ignore -- helpers.js is CommonJS
import {
  BASE_URL,
  PATHS,
  URL_PATTERNS,
  TIMEOUTS,
  dismissPostLoginOverlays,
  waitForLoaderIdle,
} from "./helpers";
import testdata from "../data/testdata.json";

// Shared Access Management helpers used by every am-* spec file.
//
// gotoAccessManagement: clicks the side-nav link, falls back to direct
// nav if the link isn't mounted, and asserts URL + h1.
//
// activateAccessManagementTab: switches to the requested tab using the
// kendo-tabstrip dynamic-id template, then confirms aria-selected="true"
// via role-based lookup (the role-based locator is stable across tab
// re-renders; the dynamic id changes on tab activation).

const AM = testdata.accessManagement;
const AM_URL = new RegExp(URL_PATTERNS.accessManagement, "i");

export async function gotoAccessManagement(page: Page): Promise<void> {
  await dismissPostLoginOverlays(page);
  await page.evaluate(() => {
    document.querySelectorAll("tm-loader .overlay").forEach((el) => {
      const h = el as HTMLElement;
      h.style.display = "none";
      h.style.pointerEvents = "none";
    });
  });
  const navLink = page.locator(AM.selectors.navLink).first();
  await navLink.click({ force: true }).catch(async () => {
    await page.goto(\`\${BASE_URL}\${PATHS.accessManagement}\`);
  });
  await expect(page).toHaveURL(AM_URL, { timeout: TIMEOUTS.navMedium });
  await waitForLoaderIdle(page).catch(() => {});
  await expect(
    page.getByRole("heading", { name: AM.heading, exact: true, level: 1 }),
  ).toBeVisible({ timeout: TIMEOUTS.elementVisible });
}

function tabByIndex(page: Page, index: number): Locator {
  return page
    .locator(AM.selectors.tabByIndexTemplate.replace("{index}", String(index)))
    .first();
}

function tabByLabel(page: Page, pattern: string): Locator {
  return page.getByRole("tab", { name: new RegExp(pattern) }).first();
}

export async function activateAccessManagementTab(
  page: Page,
  index: number,
  labelPattern: string,
): Promise<void> {
  const tab = tabByIndex(page, index);
  await expect(tab).toBeVisible({ timeout: TIMEOUTS.elementVisible });
  const selected = await tab.getAttribute("aria-selected");
  if (selected !== "true") {
    await tab.click();
    await expect(tabByLabel(page, labelPattern)).toHaveAttribute("aria-selected", "true", {
      timeout: TIMEOUTS.elementVisible,
    });
  }
  await waitForLoaderIdle(page).catch(() => {});
}
`;
fs.writeFileSync("tests/lib/am-helpers.ts", helpersTs);
console.log("Wrote tests/lib/am-helpers.ts");

// Emit one spec file per module
const moduleMap = {
  access_management: { name: "UTF-8 characters", outName: "access_management_utf8" },
  users: { name: "Users", outName: "access_management_users" },
  groups: { name: "Groups", outName: "access_management_groups" },
  departments: { name: "Departments", outName: "access_management_departments" },
  access_management_permission: { name: "Permission matrix", outName: "access_management_permissions" },
  contributor: { name: "Contributor", outName: "access_management_contributor" },
  default_group: { name: "Default group", outName: "access_management_default_group" },
  bulk_add_user_to_multiple_groups: { name: "Bulk import", outName: "access_management_bulk_import" },
  access_management_export_users: { name: "Export Users", outName: "access_management_export_users" },
};

let totalGenerated = 0;
for (const [slug, m] of Object.entries(byModule)) {
  const cfg = moduleMap[slug];
  if (!cfg) {
    console.log("Skipping unknown module:", slug);
    continue;
  }
  const file = `tests/${cfg.outName}.spec.ts`;
  fs.writeFileSync(file, generateSpec(slug, cfg.name, m.plan));
  console.log(`Wrote ${file}: ${m.plan.length} cases`);
  totalGenerated += m.plan.length;
}
console.log(`Total cases generated: ${totalGenerated}`);
